version: '3.8'

networks:
  application:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile   # ðŸ‘ˆ Updated path
    container_name: eatoo-app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - application

  nginx:
    image: nginx:latest
    container_name: eatoo-nginx
    ports:
      - "8989:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - application

  mysql:
    image: mysql:5.7
    container_name: eatoo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eatoo
      MYSQL_USER: eatoo
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - application

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eatoo-phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: eatoo-mysql
      PMA_PORT: 3306
      PMA_USER: eatoo
      PMA_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - application

volumes:
  mysql-data:
